# Database configuration for Staytus.
#
# By default, Staytus works with a MySQL database. While
# it may work with other engines, they are untested and
# currently unsupported. You can make changes to this file
# to specify the database to connect to.
# #
# But we runs with Postgresql

default: &default
  adapter: potgresql
  encoding: utf8
  port: 5432
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: staytus_test
